name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: ./.github/workflows/image.yaml
    with:
      publish: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      attestations: write
      contents: read
      packages: write
      id-token: write
      security-events: write
